### ISSUE TITLE
Errors with Readme Example

### ISSUE THREAD

**Issue by alastairlundy** [ahwm/Akismet.Net#16]
Hi,
I tried copying from the example code in the Readme and some of the code doesn't work.

I'm using the latest version of the library on Nuget in .NET 8 in ASP.NET Razor Pages. 

There is no ``Request.ServerVariables`` Dictionary property as far as I can see. Nor is there a ``Request.UserHostAddress`` property.

Likewise, there is no ``Request.UserAgent`` or ``Request.UrlReferer`` unless you're using another Nuget package to give you that.

![image](https://github.com/user-attachments/assets/353c6898-0bbc-4588-bb7b-c288408ebf84)

Also, the xml doc comments for the DateTime ``ToString`` method suggest that the ISO 8601 format is incorrect in the example. The correct usage seems to be
`DateTime.UtcNow.ToString("O");`

![image](https://github.com/user-attachments/assets/db47fb9a-9fb3-41d1-9a9f-d4037608ca1c)

For the IP address StackOverFlow seemed to suggest this code might work:
``string ip = HttpContext.Connection.RemoteIpAddress.ToString();``

Many Thanks In Advance,
Alastair :)

**Comment by ahwm** [comment]
Ah yes. I've been meaning to get around to updating that for ASP.NET Core. The Readme example is written for .NET Framework.

Some internal projects that use .NET 8 have a block like this (getting IP, user agent, and referrer):

```csharp
string ip = Request.Headers["CF-Connecting-IP"].ToString() ?? 
    _contextAccessor.HttpContext?.Connection.RemoteIpAddress?.ToString() ?? "";
if (String.IsNullOrWhiteSpace(ip))
    ip = _contextAccessor.HttpContext?.GetServerVariable("REMOTE_HOST") ?? "";
AkismetComment comment = new AkismetComment
{
    // Depending on the site, this might just be model.Name
    CommentAuthor = model.FirstName + " " + model.LastName,
    CommentAuthorEmail = model.Email,
    CommentContent = model.Message,
    CommentType = AkismentCommentType.ContactForm,
    UserAgent = Request.Headers[HeaderNames.UserAgent],
    Referrer = Request.Headers[HeaderNames.Referer],
    UserIp = ip
};
```

I regularly encounter `Connection.RemoteIpAddress` being `null` or `empty` so here I've added an additional check to use the "REMOTE_HOST" server variable in that case. This block also allows Cloudflare.

It does look like the consensus is to use "o" for ISO 8601. I was trying to find the difference between "s" and "o" and the ISO 8601 format and it seems like "s" is perfectly acceptable, minus the fractional seconds and the trailing Z. The "s" formatter has been working just fine for the `ReportHam` and `ReportSpam` operations. For check operations (as above), I actually exclude it as the docs suggest: "May be omitted for comment‑check requests if the comment is sent to the API at the time it is created."

As such, I'll probably leave it as "s" in my own projects but will update the readme.

Thanks for pointing that out.
